name: Build

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: check
        run: ./gradlew check
